// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.14.0
// source: rbac/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncPermissionsRequest_SyncType int32

const (
	SyncPermissionsRequest_USER SyncPermissionsRequest_SyncType = 0 // 同步单个用户权限
	SyncPermissionsRequest_ALL  SyncPermissionsRequest_SyncType = 1 // 同步所有权限规则
)

// Enum value maps for SyncPermissionsRequest_SyncType.
var (
	SyncPermissionsRequest_SyncType_name = map[int32]string{
		0: "USER",
		1: "ALL",
	}
	SyncPermissionsRequest_SyncType_value = map[string]int32{
		"USER": 0,
		"ALL":  1,
	}
)

func (x SyncPermissionsRequest_SyncType) Enum() *SyncPermissionsRequest_SyncType {
	p := new(SyncPermissionsRequest_SyncType)
	*p = x
	return p
}

func (x SyncPermissionsRequest_SyncType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncPermissionsRequest_SyncType) Descriptor() protoreflect.EnumDescriptor {
	return file_rbac_auth_proto_enumTypes[0].Descriptor()
}

func (SyncPermissionsRequest_SyncType) Type() protoreflect.EnumType {
	return &file_rbac_auth_proto_enumTypes[0]
}

func (x SyncPermissionsRequest_SyncType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncPermissionsRequest_SyncType.Descriptor instead.
func (SyncPermissionsRequest_SyncType) EnumDescriptor() ([]byte, []int) {
	return file_rbac_auth_proto_rawDescGZIP(), []int{2, 0}
}

// 请求和响应结构
// Authorize 请求
type AuthorizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`       // 用户身份认证的 Token
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"` // 资源名称
	Action   string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`     // 操作名称
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_rbac_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"` // 是否允许
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_rbac_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type SyncPermissionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncType SyncPermissionsRequest_SyncType `protobuf:"varint,1,opt,name=sync_type,json=syncType,proto3,enum=auth.v1.SyncPermissionsRequest_SyncType" json:"sync_type,omitempty"` // 同步类型
	UserId   string                          `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                     // 用户 ID (当 sync_type 为 USER 时必填)
	Reason   string                          `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                                   // 同步原因
}

func (x *SyncPermissionsRequest) Reset() {
	*x = SyncPermissionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPermissionsRequest) ProtoMessage() {}

func (x *SyncPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SyncPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_rbac_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPermissionsRequest) GetSyncType() SyncPermissionsRequest_SyncType {
	if x != nil {
		return x.SyncType
	}
	return SyncPermissionsRequest_USER
}

func (x *SyncPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncPermissionsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SyncPermissionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
}

func (x *SyncPermissionsResponse) Reset() {
	*x = SyncPermissionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPermissionsResponse) ProtoMessage() {}

func (x *SyncPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPermissionsResponse.ProtoReflect.Descriptor instead.
func (*SyncPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_rbac_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SyncPermissionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rbac_auth_proto protoreflect.FileDescriptor

var file_rbac_auth_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x22, 0x5c, 0x0a, 0x10, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x22, 0xaf, 0x01, 0x0a, 0x16, 0x53, 0x79, 0x6e, 0x63,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x45, 0x0a, 0x09, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1d, 0x0a, 0x08, 0x53, 0x79,
	0x6e, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x01, 0x22, 0x33, 0x0a, 0x17, 0x53, 0x79, 0x6e,
	0x63, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x51,
	0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a,
	0x09, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x6b, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d,
	0x5a, 0x1b, 0x61, 0x75, 0x74, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rbac_auth_proto_rawDescOnce sync.Once
	file_rbac_auth_proto_rawDescData = file_rbac_auth_proto_rawDesc
)

func file_rbac_auth_proto_rawDescGZIP() []byte {
	file_rbac_auth_proto_rawDescOnce.Do(func() {
		file_rbac_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_rbac_auth_proto_rawDescData)
	})
	return file_rbac_auth_proto_rawDescData
}

var file_rbac_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rbac_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rbac_auth_proto_goTypes = []interface{}{
	(SyncPermissionsRequest_SyncType)(0), // 0: auth.v1.SyncPermissionsRequest.SyncType
	(*AuthorizeRequest)(nil),             // 1: auth.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),            // 2: auth.v1.AuthorizeResponse
	(*SyncPermissionsRequest)(nil),       // 3: auth.v1.SyncPermissionsRequest
	(*SyncPermissionsResponse)(nil),      // 4: auth.v1.SyncPermissionsResponse
}
var file_rbac_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.SyncPermissionsRequest.sync_type:type_name -> auth.v1.SyncPermissionsRequest.SyncType
	1, // 1: auth.v1.AuthService.Authorize:input_type -> auth.v1.AuthorizeRequest
	3, // 2: auth.v1.AuthInternalService.SyncPermissions:input_type -> auth.v1.SyncPermissionsRequest
	2, // 3: auth.v1.AuthService.Authorize:output_type -> auth.v1.AuthorizeResponse
	4, // 4: auth.v1.AuthInternalService.SyncPermissions:output_type -> auth.v1.SyncPermissionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rbac_auth_proto_init() }
func file_rbac_auth_proto_init() {
	if File_rbac_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rbac_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPermissionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncPermissionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rbac_auth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rbac_auth_proto_goTypes,
		DependencyIndexes: file_rbac_auth_proto_depIdxs,
		EnumInfos:         file_rbac_auth_proto_enumTypes,
		MessageInfos:      file_rbac_auth_proto_msgTypes,
	}.Build()
	File_rbac_auth_proto = out.File
	file_rbac_auth_proto_rawDesc = nil
	file_rbac_auth_proto_goTypes = nil
	file_rbac_auth_proto_depIdxs = nil
}
